spring:
  application:
    name: shoppingCart

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/shoppingcart
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver