server:
  port: 8082
  servlet:
    context-path: '/ead-course'

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: admin

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  application:
    name: ead-course-service

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
      #id do eureka + context path

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

  instance:
    hostname: localhost